;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Abilities.Character.Infliction.Flinch",DevComment="")
GameplayTagList=(Tag="Abilities.Character.Infliction.Flyaway",DevComment="")
GameplayTagList=(Tag="Abilities.Character.Infliction.Knockback",DevComment="")
GameplayTagList=(Tag="Abilities.Character.Infliction.Knockdown",DevComment="")
GameplayTagList=(Tag="Abilities.Character.Infliction.Root",DevComment="")
GameplayTagList=(Tag="Abilities.Character.Infliction.Stagger",DevComment="")
GameplayTagList=(Tag="Abilities.Character.Infliction.Standup",DevComment="")
GameplayTagList=(Tag="Abilities.Character.Infliction.Stun",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Cast.End",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Combo.Combo1",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Combo.Combo2",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Combo.Combo3",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Combo.Combo4",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Combo.Combo5",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Combo.Combo6",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Combo.Combo7",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Combo.End",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Cooldown.Melee1",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Cooldown.Melee2",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Cooldown.Melee3",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Cooldown.Melee4",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Cooldown.Melee5",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Cooldown.Melee6",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Cooldown.Melee7",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Cooldown.SpecialG",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Cooldown.SpecialX",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Trigger.Melee.Combo1",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Trigger.Melee.ComboBase",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Window.Combo1",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Window.Combo2",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Window.Combo3",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Window.Combo4",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Window.Combo5",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Window.Combo6",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Window.Combo7",DevComment="")
GameplayTagList=(Tag="Combat.Damage",DevComment="")
GameplayTagList=(Tag="Combat.Damage.Stagger",DevComment="")
GameplayTagList=(Tag="Combat.State.Attacking",DevComment="")
GameplayTagList=(Tag="Combat.State.Blocking",DevComment="")
GameplayTagList=(Tag="Combat.State.Casting",DevComment="")
GameplayTagList=(Tag="Combat.State.Dead",DevComment="")
GameplayTagList=(Tag="Combat.State.Dodging",DevComment="")
GameplayTagList=(Tag="Combat.State.EaseOut",DevComment="")
GameplayTagList=(Tag="Combat.State.Invulnerable",DevComment="")
GameplayTagList=(Tag="Combat.State.ParryWindow",DevComment="")
GameplayTagList=(Tag="Combat.State.PerfectDodgeWindow",DevComment="")
GameplayTagList=(Tag="Combat.State.Sprinting",DevComment="")
GameplayTagList=(Tag="Combat.State.Untargetable",DevComment="")
GameplayTagList=(Tag="Combat.Status.Flinch",DevComment="")
GameplayTagList=(Tag="Combat.Status.Flyaway",DevComment="")
GameplayTagList=(Tag="Combat.Status.Freeze",DevComment="")
GameplayTagList=(Tag="Combat.Status.Knockback",DevComment="")
GameplayTagList=(Tag="Combat.Status.Knockdown",DevComment="")
GameplayTagList=(Tag="Combat.Status.Slow",DevComment="")
GameplayTagList=(Tag="Combat.Status.Stagger",DevComment="")
GameplayTagList=(Tag="Combat.Status.Stun",DevComment="")
GameplayTagList=(Tag="Combat.Status.Timestop",DevComment="")
GameplayTagList=(Tag="Pxii.Combat.State.ADS",DevComment="")
GameplayTagList=(Tag="Pxii.Weapon.Type.Melee",DevComment="")
GameplayTagList=(Tag="Pxii.Weapon.Type.Range",DevComment="")
GameplayTagList=(Tag="Pxii.Weapon.Type.Range.HoldToShoot",DevComment="")
GameplayTagList=(Tag="Pxii.Weapon.Type.Range.OneShot",DevComment="")
GameplayTagList=(Tag="Stat.Yang",DevComment="")
GameplayTagList=(Tag="Stat.Yin",DevComment="")

