;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Abilities.Player.Combo.Combo1",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Combo.Combo2",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Combo.Combo3",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Cooldown.Melee1",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Cooldown.Melee2",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Cooldown.Melee3",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Trigger.Melee.Combo1",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Trigger.Melee.ComboBase",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Window.Combo1",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Window.Combo2",DevComment="")
GameplayTagList=(Tag="Abilities.Player.Window.Combo3",DevComment="")

