DerivedDataCache
Intermediate
Saved
Binaries
/.vs
/.git
/.idea
.gitignore
hidden_changes.conf
cloaked.conf
*.ExternalActors/**
*.ExternalActors/*
/Content/YourMapName/ExternalActors/*
/.github
/.sln
/Content/StarterContent
*.sln
*.vsconfig
*.slnx
/Content/Developers/USER
